name: Fetch ArXiv
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
permissions: write-all

jobs:
  fetch_arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install requests
          pip install beautifulsoup4

      - name: Fetch arXiv
        run: python scrape.py

      - name: Push to repository
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'auto fetch today arXiv papers'
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com
